### ISSUE TITLE
Ghost Plugin: Member URL not Resolving

### ISSUE THREAD

**Issue by jeremycady** [TChukwuleta/BTCPayServerPlugins#65]
Donation URL works fine but receiving a 500 Error with the Member URL.

https://btcwill.win/plugins/CcHfSfR6q1tY3cC4x9aZ3kMioy37H4HK6H4Bqo7Xs4WC/ghost/public/create-member

**Comment by TChukwuleta** [comment]
Would check this out.

**Comment by TChukwuleta** [comment]
Hey @jeremycady can you install the latest version. I just bumped it now. 

Included some error handling so we can know what is failing. Let me know how it goes.. thank you

**Comment by jeremycady** [comment]
Installed the update. Page loaded but didn't have tiers. Tried a few different fixes, including uninstalling plugin, reinstalling, and setup again. 

Still not working.

Figured out, the URL needs to be the actual domain of your site, not the ghost backend url. I might suggest making a small change to docs to clarify.

Now it pulls the appropriate tiers.

On more error though. While trying to do a test subscribe, it is showing this error:
`An error occured. Value cannot be null. (Parameter 'source')`

This was on click of "Subscribe" button. The Name, email, and tier selection were all filled/selected. Not sure which value it would be referring to.

**Comment by TChukwuleta** [comment]
Just bumped a release now.. can you update and try that

**Comment by jeremycady** [comment]
Okay. Page works now. Getting an invoice when filling out the form and getting the subscribe button.

Payment is receiving just fine now. 

Webhook does not appear to be working though. Data is not updating in BTCPayServer in the Ghost Member area and is not updating in Ghost backend.

I do see a trigger of the Update Webhook. It fired when I used an email address of an account already in the system. It did not trigger when I used an email address not already in the system.

I disconnected and redid the keys just to make sure. Also redid the web secret. All appears to be correct.

**Comment by TChukwuleta** [comment]
Thank you so much @jeremycady I'd take a look to confirm nothing changed from Ghost webhook call..

Data from Ghost is meant to update BTCPay server and not the other way around. i.e. BTCPay Server does not update Ghost backend.

 However, can you explain this a lil more:

> 
" It fired when I used an email address of an account already in the system. It did not trigger when I used an email address not already in the system."

**Comment by jeremycady** [comment]
`4. Once the invoice has been paid, a member account is created by the user on the Ghost platform, the user can then proceed to log in.
`

This is not occuring. 

It is my understanding, reading the documentation, that after paying on BTCPayServer, per #4 in https://docs.btcpayserver.org/Ghost/#testing-the-membership-subscription, that an account is created for them using the Member Update webhook.

It does say that deactivation or deletion is something I must do: 
`While BTCPay Server can handle subscriptions and send notifications to the users, it cannot automatically deactivate or delete members in Ghost once a subscription ends.`

So, what I meant by fired, is that the Member Update webhook was triggered in Ghost after I paid the subscription in BTCPayServer. However, it did not update the member with a paid status and it also did not add them as a paid member in BTCPayServer.

This was only triggered when an email, already in the Ghost system, was used. When a new email was used, there was no trigger of the Member Update webhook.

**Comment by TChukwuleta** [comment]
The email you used to subscribe, when you navigate to members page on your Ghost platform, can you see the entry.. (also timestamp)..

Do you also see that email on BTCPay - Ghost plugin membership page?


When the invoice is paid, the user is created on Ghost as a member with type comped... Ghost is tightly coupled with Stripe, so if you want the user type to be paid, then it has to go through stripe. More reason why the plugin is handling subscription and reminder.

> It is my understanding, reading the documentation, that after paying on BTCPayServer, per https://github.com/TChukwuleta/BTCPayServerPlugins/pull/4 in https://docs.btcpayserver.org/Ghost/#testing-the-membership-subscription, that an account is created for them using the Member Update webhook.

Paying the invoice does not trigger a webhook call.. what triggers a webhook call is when you update the member on Ghost, or delete the member on Ghost... then the same details should reflect on BTCPay Server

> So, what I meant by fired, is that the Member Update webhook was triggered in Ghost after I paid the subscription in BTCPayServer. However, it did not update the member with a paid status and it also did not add them as a paid member in BTCPayServer.


Yes, Ghost does not allow external API calls to delete or deactivate a member
> It does say that deactivation or deletion is something I must do:

Let me know if there is still a confusion somewhere, or a different behaviour you are experiencing with the plugin

**Comment by jeremycady** [comment]
Got it. Thank you.

So the steps are:
1. They pay in BTCPayServer
2. I go into Ghost and add them and them comp them for the time they paid for.
3. When they expire, I remove them in Ghost.

Got it. Then the only issue I currently see is, they are not updating in Ghost Members in the BTCPayServer side. I'll need to make a new store so I can setup mail specifically for those invoices in Ghost, so I know when I need to add someone.

**Comment by jeremycady** [comment]
`BTC-CHAIN: Invoice amount below accepted value for payment method`

**Comment by jeremycady** [comment]
Using amounts for $5 USD. 

Invoices were paid. 

The above error is the only one I see.

**Comment by jeremycady** [comment]
```
btcpay-server_web_1        | info: PayServer:      BTC (Lightning): Payment detected via notification (LN Invoice)
btcpay-server_web_1        | info: PayServer:      BTC (Lightning): No more invoice to listen on https://10.21.21.9:8080/, releasing the connection
btcpay-server_web_1        | fail: PayServer:      Ghost error while trying to create member on Ghost platform. Object reference not set to an instance of an object.Triggered by invoiceId: LN Invoice
btcpay-server_web_1        | System.NullReferenceException: Object reference not set to an instance of an object.
btcpay-server_web_1        |    at BTCPayServer.Plugins.GhostPlugin.Services.GhostHostedService.RegisterMembershipCreationTransaction(InvoiceEntity invoice, String orderId, Boolean success) in /build/Plugins/BTCPayServer.Plugins.GhostPlugin/Services/GhostHostedService.cs:line 156
```

**Comment by TChukwuleta** [comment]
thanks

**Comment by TChukwuleta** [comment]
Hey man @jeremycady  

Apologies I was unavailable yesterday... 


Did a bump... can you update your plugin and try again.. 

Can you create a new member and confirm if the behaviour has been corrected or just as you experience. 

Let me know. Thanks

**Comment by jeremycady** [comment]
No need to apologize. I'm not in a hurry and I appreciate your help.

Still not adding it to the ghost member area in BTCPayServer.

Here is the error I see.

```
fail: BTCPayServer.Plugins.GhostPlugin.Services.GhostPluginService: Ghost Plugin: An error occurred while sending email to member https://btcwill.win/plugins/H5SLZXHWeWLG53nRx2YABDbkHqJ8MZo2vTjQxT6ZKiq6/ghost/public/create-member: System.InvalidOperationException: Sequence contains no elements
btcpay-server_web_1        |          at System.Linq.ThrowHelper.ThrowNoElementsException()
btcpay-server_web_1        |          at lambda_method1073(Closure, QueryContext)
btcpay-server_web_1        |          at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
btcpay-server_web_1        |          at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
btcpay-server_web_1        |          at BTCPayServer.Plugins.GhostPlugin.Services.GhostPluginService.HandleActiveSubscriptionCloseToEnding() in /build/Plugins/BTCPayServer.Plugins.GhostPlugin/Services/GhostPluginService.cs:line 178
```

**Comment by TChukwuleta** [comment]
Noted that.

You did make a new payment yea? 

If you go to Invoice -> selected invoices and scroll down.. 

under events (see image) do you see any error?

![Image](https://github.com/user-attachments/assets/7776f129-8222-4e33-90e8-ab190c86f74f)

**Comment by jeremycady** [comment]
No, not on mattermost. I made a new payment, yes. A couple to test. 

These are the  invoice events.

<img width="773" alt="Image" src="https://github.com/user-attachments/assets/cab4475b-681c-4a4e-99ce-f0fc89a5bb58" />

**Comment by TChukwuleta** [comment]
Hey @jeremycady  and no record shows still?

If so, can you join Mattermost https://chat.btcpayserver.org/ and message me @tobses on mattermost

**Comment by TChukwuleta** [comment]
This is completed.
